WebMonitor/WebMonitor/urls.py
from django.contrib import admin
from django.urls import include, path
from monitor.views import monitor_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitor.urls', namespace='monitor')),
    path('api/', include('api.urls', namespace='api')),
]

WebMonitor/api/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import FailuresViewSet, WebPageViewSet

app_name = 'api'

router = routers.DefaultRouter()

router.register(r'webpage-viewset', WebPageViewSet) 
router.register(r'failure-viewset', FailuresViewSet) 

urlpatterns = [
    path('', include(router.urls)),
]

WebMonitor/monitor/urls.py
from django.urls import path

from .views import AddWebPageView, WebPageDeleteView, WebPageDetailView, WebPageUpdateView, broken_webpages_view, monitor_view

app_name = 'monitor'

urlpatterns = [
    path('', monitor_view, name='main'),
    path('broken-webpages/', broken_webpages_view, name='BrokenWebpages'),
    path('<pk>/delete/', WebPageDeleteView.as_view(), name='webpage-delete'),
    path('<pk>/update/', WebPageUpdateView.as_view(), name='webpage-update'),
    path('<pk>/detail/', WebPageDetailView.as_view(), name='webpage-details'),
    path('add-webpage/', AddWebPageView, name='AddWebPage'),
]

WebMonitor/api/models.py
from django.db import models

# Create your models here.

WebMonitor/monitor/models.py
from django.db import models
import datetime
# Create your models here.

class Failure(models.Model):
    PageName = models.TextField(default="This webpage")
    StatusCode = models.TextField(default="This webpage")
    FailureTimeBegin = models.DateTimeField(default=datetime.datetime.now)
    FailureTimeFixed = models.DateTimeField(blank=True,null=True)
    ResponseDataOnFailure = models.TextField(blank=True)
    ResponseDataAfterFix = models.TextField(blank=True)
    LogErrorMessage = models.TextField(blank=True)
    
class WebPage(models.Model):
    description = models.TextField(blank=True)
    link = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    WebPageName = models.TextField(default="Web Page")
    Failures = models.ManyToManyField(Failure, blank=True, related_name='Failures')
    IsWorking = models.BooleanField(default=True)
    FrequencyOfChecking=models.TextField(default="1min")

WebMonitor/monitor/forms.py
from django import forms
from .models import WebPage

class WebPageModelForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    link = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    WebPageName = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    CHOICES = (('1min', 'Once per minute'),('5min', 'Every 5 minutes'),('1hour', 'Once per hour'),('1day', 'Once per day'),)
    FrequencyOfChecking = forms.ChoiceField(choices=CHOICES)
    class Meta:
        model = WebPage
        fields = ('link' ,'WebPageName','description','FrequencyOfChecking' )

WebMonitor/api/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from .serializers import FailureSerializer, WebPageSerializer
from monitor.models import WebPage , Failure
from rest_framework import viewsets

class WebPageViewSet(viewsets.ModelViewSet):
   
    serializer_class = WebPageSerializer
    queryset = WebPage.objects.all()

class FailuresViewSet(viewsets.ModelViewSet):
    serializer_class = FailureSerializer
    queryset = Failure.objects.all()

WebMonitor/monitor/views.py
from pickle import EMPTY_LIST
from django.shortcuts import redirect, render
from django.views.generic import UpdateView, DeleteView, DetailView
from .forms import WebPageModelForm
from .models import WebPage, Failure
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


# Create your views here.
def monitor_view(request):
    WebPages = WebPage.objects.all()
    context = {
        'WebPages': WebPages,
        
    }
    
    return render(request, 'monitor/monitoring.html', context)

def broken_webpages_view(request): 
    WebPages = WebPage.objects.filter(IsWorking=False)
    context = {
        'WebPages': WebPages,
    }
    return render(request, 'monitor/BrokenWebpages.html', context)


def AddWebPageView(request):
    form = WebPageModelForm(request.POST or None, request.FILES or None, )

    if request.method == 'POST':
        if form.is_valid():
            
            form.save()
            return redirect('monitor:main')

    context = {
        'form': form,
        }

    return render(request, 'monitor/AddNewWebPage.html', context)


class WebPageDeleteView(DeleteView):
    model = WebPage
    template_name = 'monitor/confirm_delete.html'
    success_url = reverse_lazy('monitor:main')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = WebPage.objects.get(pk=pk)
        return obj


class WebPageUpdateView(UpdateView):
    form_class = WebPageModelForm
    model = WebPage
    template_name = 'monitor/update.html'
    success_url = reverse_lazy('monitor:main')

    def form_valid(self, form):
        return super().form_valid(form)

class WebPageDetailView(DetailView):
    model = WebPage
    template_name = 'monitor/WebPage_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        page = WebPage.objects.get(pk=pk)
        QFailures = page.Failures.all()
        context['page'] = page
        context['QFailures'] = QFailures
        return context

WebMonitor/monitor/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!--Custom css-->
    <link rel="shortcut icon" type="image/ico" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <title>WebMonitor</title>


  </head>
  <body>
   <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    {% include 'navbar.html' %}
    <div class="ui container" style="width: 1200px; ">
      {% block content %}
      {% endblock content %}
    </div>
    {% block scripts %}
    {% endblock scripts %}
   <!--Custom js ADD-->
   <script type="text/javascript" src={% static 'js/main.js' %}></script>
  </body>
</html>

WebMonitor/monitor/templates/monitor/AddNewWebPage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  add new post
{% endblock title %}

{% block content %}
  <div class="ui segment " style="width: 1000px;margin: 0 auto;">

    <div class="ui header">
      <h1 class="ui aligned center  header massive">Add new Website</h1>
      <div class="ui fitted divider"></div>
    </div>

    <div class="ui grid">
      <div class="column">
        <div class='ui block'>

 <form action="" method="POST" class="ui form" enctype='multipart/form-data'>

          {% csrf_token %}
          <h3 style="margin: 10px 0 0 0;">Name of website</h3>
          {{ form.WebPageName }}
          <h3 style="margin: 10px 0 0 0;">Link (format: https://www.youtube.com/)</h3>
          {{ form.link }}
   <h3 style="margin: 10px 0 0 0;">Description</h3>
          {{ form.description }}
          <div class="ui small header">Choose Frequency of checking website</div>
           <p> {{ form.FrequencyOfChecking }}</p</>
          <div class="actions" >
            <button type='submit' style=" width: 500px;" class="ui positive right labeled icon button ">
              Add new Website

            </button>
          </div>

          </form>

        </div>


      </div>

    </div>

  </div>
{% endblock content %}

WebMonitor/monitor/templates/monitor/BrokenWebpages.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  my profile
{% endblock title %}

{% block content %}
{% url 'monitor:AddWebPage' as path_to_add_webpage %}
<div class="ui segment">
  
    <div class="ui three column grid">
        {% if WebPages %}
        {% for obj in WebPages %}
  
          <div class="column">
  
            <div class="ui fluid card " style="position: relative;top: 0; left: 0;">
  
              
                <div class="image outer ">
  
                  <img style="height: 350px;width: 100%; object-fit: cover; position: relative;top: 0;left: 0;" src={% static "images/IsNotWorking.png" %}>
  
                </div>
              </a>
  
              <div class="content">
                <div class="ui three column pagged grid center aligned">
                  <div class="column">
                    <a class="ui button bwhite-lg" href="{% url 'monitor:webpage-update' obj.pk %}">
                      Update
                    </a>
                  </div>
                  <div class="column">
                    <a class="ui button bwhite-lg ">
                      Detais
                    </a>
                  </div>
                  <div class="column">
                    <a class="ui button bwhite-lg" href="{% url 'monitor:webpage-delete' obj.pk %}">
                      Remove
                    </a>
                  </div>
                </div>
                <div class="ui divider"></div>
  
                <div class="content">
                  <div class="header">{{obj.WebPageName}}</div>
                  <div class="meta">
                    <span class="date">{{obj.link}}</span>
                  </div>
                  <div class="description">
                    {{obj.description}}
                  </div>
                </div>
  
               
              </div>
              
            </div>
  
          </div>
          
        {% endfor %}
        {% else %}
        <h1 class="ui header">No broken webpage found</h1>
        {% endif %}
      </div>
  
    </div>
</div>
{% endblock content %}

WebMonitor/monitor/templates/monitor/WebPage_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}WebPage{% endblock title %}

{% block content %}


  <div class="ui segment">

    
    <div class="ui grid">
      <div class='row'>
        <div class='eight wide column'>
          

            <div class="image outer ">
                {% if page.IsWorking %} 
                <img style="height: 450px;width: 100%; object-fit: cover; position: relative;top: 0;left: 0;" src={% static "images/IsWorking.png" %}>
                {% else %}
                <img style="height: 450px;width: 100%; object-fit: cover; position: relative;top: 0;left: 0;" src={% static "images/IsNotWorking.png" %}>
                {% endif %}
              </div>

          <div class="ui centered ">
            <div class="content">

              <div class="ui header centered mt-5"><h1>{{ page.WebPageName }}</h1></div>

              
            </div>
          </div>
        </div>
        <div class='eight wide column'>

          <div class="ui segment">
            <div class="content">

              <div class="header"><h1>{{ page.WebPageName }}</h1></div>

              <div class="description">
                <div class="header">
                    <h3>Description</h3>
                  </div>
                <h4>{{ page.description }}</h4>
                <div class="header">
                  <h2>Link</h2>
                </div>

                <h3>{{page.link }}</h3>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>




      <div class="ui divider"></div>
      <div class="ui header centered"> Failures</div>

      <div class="ui three column grid">
       {% if QFailures %}
      {% for obj in QFailures %}
        <div class="column">
          <div class="ui fluid card ">
            <div class="image ">
              <img style="height: 350px;width: 100%; object-fit: cover;" src={% static "images/Failure.png" %}>
            </div>
            <div class="content">
              <a class="header">{{obj.PageName}}</a>
              <div class="meta">
                <span class="date">{{obj.FailureTimeBegin}} - {{obj.FailureTimeFixed}}</span>
                <div class="description">
                  Status code - {{obj.StatusCode}}
                </div>
              </div>
              
            </div>
          </div>
        </div>
      {% endfor %}
      {% else %}
      <h1 class="ui header " style="margin: 0 auto;">No failure history</h1>
      {% endif %}
     
      

    </div>
  </div>

{% endblock content %}

WebMonitor/monitor/templates/monitor/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
delete post
{% endblock title %}

{% block content %}


        <div class="ui segment " style="width: 50%; margin:  20px auto 0px auto; text-align: center;">

            <form  action="" method="POST">
                {% csrf_token %}
              <br/>
              <h2>Are you sure you want remove this Website?</h2>
              <br/>
               <button type="button" class="ui secondary button massive labeled icon " onClick="javascript:history.go(-1);"><i class="left arrow icon"></i>Back</button>
                <button class="ui button negative massive centered right labeled icon"    type='submit'><i class=" trash alternate icon"></i>Remove</button>

            </form>
        </div>

{% endblock content %}

WebMonitor/monitor/templates/monitor/monitoring.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  my profile
{% endblock title %}

{% block content %}
{% url 'monitor:AddWebPage' as path_to_add_webpage %}
<div class="ui segment" >
  <div class="ui right close rail">  

    <a class="ui icon big button" href="{{path_to_add_webpage}}">
      <i class="add icon   gray"  }></i>
      Add Website
    </a>
   
  </div>
    <div class="ui three column grid" >
      {% if WebPages %}
      
        {% for obj in WebPages %}
  
          <div class="column">
  
            <div class="ui fluid card " style="position: relative;top: 0; left: 0;">
  
              
                <div class="image outer ">
                  {% if obj.IsWorking %} 
                  <img style="height: 350px;width: 100%; object-fit: cover; position: relative;top: 0;left: 0;" src={% static "images/IsWorking.png" %}>
                  {% else %}
                  <img style="height: 350px;width: 100%; object-fit: cover; position: relative;top: 0;left: 0;" src={% static "images/IsNotWorking.png" %}>
                  {%endif %}
                </div>
              </a>
  
              <div class="content">
                <div class="ui three column pagged grid center aligned">
                  <div class="column">
                    <a class="ui button bwhite-lg" href="{% url 'monitor:webpage-update' obj.pk %}">
                      Update
                    </a>
                  </div>
                  <div class="column">
                    <a class="ui button bwhite-lg " href="{% url 'monitor:webpage-details' obj.pk %}">
                      Detais
                    </a>
                  </div>
                  <div class="column">
                    <a class="ui button bwhite-lg" href="{% url 'monitor:webpage-delete' obj.pk %}">
                      Remove
                    </a>
                  </div>
                </div>
                <div class="ui divider"></div>
  
                <div class="content">
                  <div class="header">{{obj.WebPageName}}</div>
                  <div class="meta">
                    <span class="date">{{obj.link}}</span>
                  </div>
                  <div class="description">
                    {{obj.description}}
                  </div>
                </div>
  
               
              </div>
              
            </div>
  
          </div>
          
        {% endfor %}
      
        {% else %}
        <h1 class="ui header">No websites currently is monitoring, add some.</h1>
        {% endif %}
      </div>
  
    </div>
</div>
{% endblock content %}

WebMonitor/monitor/templates/monitor/update.html
{% extends 'base.html' %}
{% load materializecss %}
{% block title %}
update WebPage
{% endblock title %}
{% block css %}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous"/>
{% endblock css %}
{% block content %}
    <div class='ui segment' style="width: 50%; margin:  20px auto 0px auto; text-align: center;">
        <h1>Update Website</h1>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="ui small header">Name of website</div>
           <p> {{ form.WebPageName}}</p>
           <div class="ui small header">Link (format: https://www.youtube.com/)</div>
           <p> {{ form.link}} </p>
           <div class="ui small header">Description</div>
           <p> {{ form.description}}</p>
           <div class="ui small header">Choose Frequency of checking website</div>
           <p> {{ form.FrequencyOfChecking }}</p</>
            <button type='submit' class="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}s

WebMonitor/monitor/templates/navbar.html
{% load static %}

{% url 'monitor:main' as path_to_main %}
{% url 'monitor:BrokenWebpages' as path_to_broken_webpages %}

<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"/>
<nav class="navmenu">
  <ol>
    <li class="menu-item">
      <a style="display: flex;" href="{{path_to_main}}" >
        <!-- {% load static %}<img  class="ui image mini centered " style="margin-bottom:5px;" src={% static "images/WebMonitor.png" %} alt="logo"> -->
        <span style="margin:0 auto;">WebMonitor</span>
      </a>
    </li>
   
      <li class="menu-item" ><a href="{{path_to_broken_webpages}}">Broken Websites</a></li>
      
      
  </ol>
</nav>